services:
  mongo:
    image: mongo:latest
    container_name: ekyc-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: ekyc-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:4-management
    container_name: ekyc-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  ekycfe:
    image: shaw0n/kycfe:dev
    container_name: ekyc-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - ekycbe

  ekycbe:
    build:
      context: ./backend
      dockerfile: dockerfile
    image: shaw0n/ekycbe:dev
    container_name: ekyc-backend
    restart: always
    environment:
      MONGO_URI: mongodb://admin:qwerty@mongo:27017/ekyc?authSource=admin
      RABBITMQ_URL: amqp://rabbitmq
      PORT: 5001
      OPENROUTER_API_KEY: YOUR_API_KEY
      JWT_SECRET: supersecretkey123
      JWT_EXPIRES: 3600
    ports:
      - "5001:5001"
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  pdf-worker:
    build:
      context: ./backend
      dockerfile: dockerfile
    image: ekycbe:dev
    container_name: ekyc-pdf-worker
    restart: always
    command: ["npm", "run", "worker"]
    environment:
      MONGO_URI: mongodb://admin:qwerty@mongo:27017/ekyc?authSource=admin
      RABBITMQ_URL: amqp://rabbitmq
      OPENROUTER_API_KEY: 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
    volumes:
      - pdf-data:/app/pdfs
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  

volumes:
  mongo-data:
  rabbitmq-data:
  pdf-data:

